version: '3.8'

services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - weather-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
  weather-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: weather-api
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - spring.redis.host=redis
      - spring.redis.port=6379
      - weather.api.key=HTX8K4ACP6B87PJLU6NRYAVPD
    networks:
      - weather-net

networks:
  weather-net: