spring.application.name=weather-api

# Redis
#spring.cache.type=redis
#spring.redis.host=redis
#spring.redis.port=6379


# API de clima
weather.api.base-url=https://weather.visualcrossing.com
weather.api.key=HTX8K4ACP6B87PJLU6NRYAVPD

logging.level.org.springframework.boot.autoconfigure.data.redis=DEBUG
